## Problem statement
The following assignment concerns the numpy.random package in Python [2]. You are required to create a Jupyter [5] notebook explaining the use of the package, including detailed explanations of at least five of the distributions provided for in the package. 

**There are four distinct tasks to be carried out in your Jupyter notebook:** 
1. Explain the overall purpose of the package.
2. Explain the use of the “Simple random data” and “Permutations” functions.
3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers.


In [8]:
import numpy

In [11]:
for i in range(10):
    print(random.random())

0.37531628017153973
0.9802034714354388
0.3109095298636859
0.9142912271466794
0.30960604545065795
0.24557923334284526
0.30655089140179725
0.879948934300795
0.8089447176190708
0.8663285501172305


In [12]:
def my_random():
    return 4*random.random() + 3

for i in range(10):
    print(my_random())

3.356802063948651
3.1662266992108803
6.760929355617986
4.7933925105450985
3.5861619597501257
6.038881926253042
4.754692632417672
3.8553888598643535
5.188489072049226
3.6609118753508385


In [13]:
for i in range(10):
    print(random.uniform(3, 7))

6.667991689210915
5.195151495350453
4.805079604275679
6.286429499122683
4.84338605777012
3.371587380796232
3.6339894901894323
4.790924597617696
4.8104205310678045
3.764015717428688


In [14]:
for i in range(20):
    print(random.normalvariate(0,  9))

6.8841864268835415
6.044258323883702
11.436624519710348
-3.0762235332244026
-0.841428621597965
14.943849631694
-17.172463434824667
-0.16808813366449923
2.719497541143213
-10.581919337936341
4.533953522595604
9.617657158355724
-1.6592859960955453
2.708745579278615
6.110511620829451
16.065427204676528
1.3705347856593393
-1.1706194205043126
12.352634466255287
9.130667486000977


### Backgrond info.

#### What is numpy?
It is a way of creating 1D, 2D, 3D, 4D arrays etc 

Why do we use Numpy arrays instead of lists.
**Lists are slow, Numpy is fast**

**Why is this?**
One reason is because Numpy uses fixed types.


| |  |  | |
|---|---|---|---|
|3|1|2|4|
|5|7|1|2|
|4|1|0|1|

* Imagine that we have a 3 by 4 matrix, all integer values, we will look at how they differ between Numpy and list.

* In the table above the numpy 5 is interpreted as the binary number 00000101 - Numpy will cast this 5 an int.32 bit (this consits of 4 bites). 

* On the other hand, lists use a built in int. type that consist of 4 things (the object value, obj type, the reference count and the size of the int. value). Breaking this down into the binary that a list represents, the first 3 list types have 8 bits. This makes the memory space required for lists much larger.

* Another reason for this, when iterating though each item in a numpy array, you don't have to have a type cheak each time. Because Numpy only has one type. 

* Wemory blocks utilised by a list are often split up within the memory. This means a list just contains many pointers leading to the memory blocks within the memory. This measn that lists are quite slow.

* In contrast, Numpy also uses contiguous memory. This means that all memory blocks are right next to each other. This is much easier than the pointer-structure of lists. The first benefit of this is that CPU's are utilised better when memory blocks are near each other, i.e. many computations can be done on contiguous memory at the same time.

* It also leads to effective cache utilisation. When array values are loaded in, they can all be loaded in at the same time in one load.

### What can we do with Numpy that can't be done with lists.

|Lists | Numpy|
|:---:| :---: |
|Insertion, deletion, appending, concatenation etc.| Insertion, deletion, appending, concatenation etc. + LOTS more |

| Multiplying lists | Multiplying arrays |
| :---: | :---: |
| a = [1,3,5] | a = np.array([1,3,5]) |
| b = [1,2,3] | b = np.array([1,2,3])|
| a * b = ERROR | a * b = np.array([1,6,15])

#### Applications of Numpy

* Mathematics (MATLAB Replacement)
* Plotting (Matplotlib)
* Backend (Pandas, Connect 4, Digital Photography)
* Machine learning - 'tenser' libraries are similar to Numpy

#### Coding with Numpy

In [2]:
import numpy as np

##### The basics

In [71]:
a = np.array([1,2,3], dtype = 'int32')
print(a)

[1 2 3]


In [72]:
b = np.array([ [9.0, 8.0, 7.0], [6.0, 5.0, 4.0] ])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [73]:
# Get dimensions
a.ndim

1

In [74]:
b.ndim

2

In [75]:
# Get shape
a.shape

(3,)

In [76]:
b.shape

(2, 3)

In [77]:
# Get type
a.dtype

dtype('int32')

In [78]:
b.dtype

dtype('float64')

In [79]:
# Get size
a.itemsize

4

In [80]:
b.itemsize

8

In [81]:
# Get total size
a.size # (total number of elements)

3

In [82]:
b.size

6

In [83]:
a.nbytes # (the same as a.size * a.itemsize)

12

In [84]:
b.nbytes

48

#### Accessing/Changine specific elements, rows, columns, etc.

In [121]:
a = np.array ([ [1, 2, 3, 4, 5, 6, 7],[8,9,10,11,12,13,14] ])

In [88]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [89]:
# Get a specific element
a[1, 5]

13

In [90]:
# Using negative notation
a[1, -2]

13

In [92]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [93]:
a[:, 2]

array([ 3, 10])

In [97]:
# Getting more nuanced outputs
a[0, 1:6:2]

array([2, 4, 6])

In [98]:
a[0, 1:-1:2]

array([2, 4, 6])

In [100]:
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [102]:
a[:,2] = 5
print(a)

[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]]


In [105]:
a[:,2] = [1,2]
print(a)

[[5 5 1 5 5 5 5]
 [5 5 2 5 5 5 5]]


#### 3-d example

In [106]:
b = np.array( [ [[1,2], [3,4] ], [ [5,6], [7,8] ] ])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [107]:
# Get specific element (work outside in)
b[0, 1, 1]

4

In [108]:
b[:, 1: ]

array([[[3, 4]],

       [[7, 8]]])

In [ ]:
# Replace
b[:, 1: ] = [ [9,9], [8, 8] ]

#### Initialising Different Types of Arrays

In [113]:
# ALL 0's matrix
np.zeros( (2,3) )

array([[0., 0., 0.],
       [0., 0., 0.]])

In [117]:
# ALL 1's in matrix
np.ones( (4,2,2), dtype = 'int32' )

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [120]:
# Any other number
np.full( (2,2) , 99, dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [125]:
# Any other number (full_like method) to create an array of 4's etc,
# for a shape already used in a previous array
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [129]:
# Random decimal number (random_sample method)
np.random.random_sample(a.shape)

array([[0.12215718, 0.12422452, 0.78907686, 0.80388721, 0.68035937,
        0.34593217, 0.13386641],
       [0.58085149, 0.97861637, 0.35905845, 0.34205087, 0.88053344,
        0.23651948, 0.69087075]])

In [131]:
# Random integer values
np.random.randint(7, size=(3,3))

array([[3, 2, 3],
       [2, 0, 3],
       [5, 6, 5]])

In [148]:
np.random.randint(-4, 8, size=(3,2))

array([[ 6, -4],
       [ 7, -1],
       [ 1,  4]])

In [137]:
# Identity matrix (only 1 parameter needed)
np.identity(5)

# Note this always produces a square matrix (e.g. 5 * 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [143]:
# Repeat an array a few times
arr = np.array( [ [1, 2, 3] ] )
r1 = np.repeat(arr, 3, axis=0 )
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


| - | - | - | - | - |
|---|---|---|---|---|
| 1 | 1 | 1 | 1 | 1 |
| 1 | 0 | 0 | 0 | 1 |  
| 1 | 0 | 9 | 0 | 1 | 
| 1 | 0 | 0 | 0 | 1 | 
| 1 | 1 | 1 | 1 | 1 | 


##### Creating the array depicted by the numbers in the above table:

In [152]:
output = np.ones( (5,5) )
print(output)

z = np.zeros( (3, 3) )

z[1,1] = 9

print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [153]:
# Place z inside 'output'
output[ 1:4, 1:4 ] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays

In [155]:
a = np.array( [1, 2, 3] )
b = a
print(b)

[1 2 3]


In [157]:
b[0] = 100
print(b)

[100   2   3]


In [158]:
print(a)

[100   2   3]


##### Note: that in the above examples, the alteration made to the first element of b is carried through to a as well.

Because of the variable operations in Python, by setting b = a, we told Python that b points to the same list as a, therefore, both variables are getting their values from the same bucket and any alterations made to an element of b will be carried through to a.

##### In the below example the variable d is pointed towards a.copy. When .copy is used on a variable, any alteration is not made to the original list.

In [160]:
c = a.copy()
c[0] = 200
print(c)

[200   2   3]


In [161]:
print(a)

[100   2   3]


### Mathematics
One of the primary use of Numpy is the varied type of maths it can perform.

In [171]:
a = np.array( [1, 2, 3, 4] )
print(a)

[1 2 3 4]


In [172]:
a + 2

array([3, 4, 5, 6])

In [173]:
a - 2

array([-1,  0,  1,  2])

In [174]:
a * 2

array([2, 4, 6, 8])

In [175]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [176]:
a += 2
print(a)

[3 4 5 6]


In [177]:
b = np.array( [1, 0, 1, 0] )

In [178]:
a + b

array([4, 4, 6, 6])

In [179]:
a ** 2

array([ 9, 16, 25, 36], dtype=int32)

In [182]:
# Take the sign of all the values
np.sin(a)
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

#### Linear Algebra

In [185]:
a = np.ones( (2, 3) )
print(a)

b = np.full( (3, 2), 2 )
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [186]:
# Matrix Multiplication
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [188]:
# Determinant 
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics with Numpy

In [189]:
stats = np.array( [ [1, 2, 3], [4, 5, 6] ] )
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [190]:
np.min(stats, axis = 0)

array([1, 2, 3])

In [192]:
np.max(stats, axis = 1)

array([3, 6])

In [193]:
np.sum(stats, axis=0)

array([5, 7, 9])

#### Reorganising Arrays

In [194]:
before = np.array( [ [1, 2, 3, 4], [5, 6, 7, 8] ] )
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [198]:
after = before.reshape((2, 2, 2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [201]:
# Veritcal Staking matrixes
v1 = ([1, 2, 3, 4])
v2 = ([5, 6, 7, 8])

np.vstack( [v1, v2, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [204]:
# Horizontal Stacking
h1 = np.ones( (2, 4) )
h2 = np.zeros( (2, 2) )

np.hstack( (h1, h2 ) )

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Miscellaneous Uses of Numpy

In [209]:
# Load data from a file
data5 = np.genfromtxt('data5.txt', delimiter=',' )
print(data5)

[[nan nan nan nan nan]
 [nan nan nan nan nan]
 [5.1 3.5 1.4 0.2 nan]
 [4.9 3.  1.4 0.2 nan]
 [4.7 3.2 1.3 0.2 nan]
 [4.6 3.1 1.5 0.2 nan]
 [5.  3.6 1.4 0.2 nan]
 [5.4 3.9 1.7 0.4 nan]
 [4.6 3.4 1.4 0.3 nan]
 [5.  3.4 1.5 0.2 nan]
 [4.4 2.9 1.4 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]]


In [210]:
data5.astype('int32')
data5

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan],
       [5.4, 3.9, 1.7, 0.4, nan],
       [4.6, 3.4, 1.4, 0.3, nan],
       [5. , 3.4, 1.5, 0.2, nan],
       [4.4, 2.9, 1.4, 0.2, nan],
       [4.9, 3.1, 1.5, 0.1, nan]])

##### Boolean Masking and Advanced Indexing

In [216]:
# Extracting the vectors from a data file that are greater than 5
data5[data5 > 5]

<ipython-input-216-af58febc9b87>:1: RuntimeWarning: invalid value encountered in greater
  data5[data5 > 5]


array([5.1, 5.4])

In [219]:
# Checking through each column to see what columns 
# contain a value greater than 5.
np.any(data5 > 4, axis = 0 )

<ipython-input-219-196172771c52>:3: RuntimeWarning: invalid value encountered in greater
  np.any(data5 > 4, axis = 0 )


array([ True, False, False, False, False])

In [220]:
# Setting a range for extracting values within
( ( data5 > 4) & (data5 < 4.5 ) )

<ipython-input-220-28bea8fe32f9>:2: RuntimeWarning: invalid value encountered in greater
  ( ( data5 > 4) & (data5 < 4.5 ) )
<ipython-input-220-28bea8fe32f9>:2: RuntimeWarning: invalid value encountered in less
  ( ( data5 > 4) & (data5 < 4.5 ) )


array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

##### Index matrix including 6, 8, 12, 13

|-|-|- |- |- |
|---|---|---|---|---|
|1 |2 |3 |4 |5 |
|6 |8 |9 |10 |11 |
|12 |13 |14 |15 |16 |
|17|18 |19 |20 |21 |
|22 |23 |24 |25 |26 |
|27 |28 |29 |30 |31 |