## Q2: Explain the use of the “Simple random data” and “Permutations” functions.

In [2]:
import numpy as np
import matplotlib.pyplot as plt

### 2.1. Simple Random Data

#### 2.1.1. What do the Simple Random Data Functions Do?
The second section of the numpy.random package relates to the use of simple random data. This sections contains 4 functions that return random values of various types. The four functions are:
1. integers
2. random
3. choice
4. bytes

Numpy's classification of its Random package into three groups (Simple Random Data, Permuations and Distributions) may not be immediately intuitive when first using the package. However, by practicing the use of functions from each of these groups, one can grasp the distinctions between them. The Permutation functions can take an ordered array as input and output either a shuffled version or a new variable that has been 'randomly' permuted. The Distribution functions all produce random data that reflects a particular statistical distribution. 

However, the functions under in Simple Random Data section are, it could be argued, the most random of the entire numpy.random package. In the case of the random.integers() and random.random() functions, the output is manipulated based on type (integer or floating point number). Whereas, in the case of the random.choice function(), the random data produced can be set at a specific probability, providing a useful means to replicate rea-life 'chance' scenarios, such as the simulation of a game of roulette. The bytes() function is limited to producing random bites of a given length. These functions have broad use across all probabilities and areas of statistics. They are less concerned with producing manipulated data and are designed to provide the most basic statistical ramdomisation tools. 

#### 2.1.2. Producing Arrays of Simple Random Data

#### random.integers() 

In [13]:
rng = np.random.default_rng()

# Produce a 2 by 3 array between 1 and 10
print(rng.integers(10, size=(2, 3)) )

# Produce a 4 by 5 array between 1 and 20
print("\n", rng.integers(20, size=(4, 5)) )

[[5 6 2]
 [6 4 4]]

 [[15  6  0  7 13]
 [ 1 10 18 11 19]
 [19  0  9 12 11]
 [ 2 17 14  9  1]]


In [15]:
# prduce a matrix of integers between 1 and 48 in 4-d
print("\n", rng.integers(48, size=(2, 2, 3, 4)) )


 [[[[28 27 10 23]
   [17  5 20 10]
   [ 6 47 15 46]]

  [[29 22 14  8]
   [27 12 18 37]
   [34 43 15 15]]]


 [[[19 44 25 22]
   [24  6  5  1]
   [35 47 25 13]]

  [[ 4 42 15 16]
   [33 12 36 43]
   [ 9  4  4  9]]]]


### 2.2. Permutation Functions

##### Definition (Webster's Dictionary)
*permute (pəˈmjuːt)*
*vb (tr)*

1. *to change the sequence of*
2. *(Mathematics) to subject to permutation [C14: from Latin permūtāre, from per- + mūtāre to change, alter] perˈmutable adj perˌmutaˈbility, perˈmutableness n perˈmutably adv*

Accrding to corporatefinanceinstitute.com, a permutation is a mathematical technique that determines the number of possible arrangements in a set when the order of the arrangements matters. Common mathematical problems involve choosing only several items from a set of items with a certain order.

There are two functions within Numpy's Permutations Section:
* The Shuffle function

*and*
* The Permutation function

Both of these function, permute a list in order to create random data. In particular, they both change the order of elements in an array. However, whist shuffle() merely permutes an array and outputs the altered array, permutation() makes a copy of an array, permutes it and then outputs the change in the form of a new variable.

#### 2.2.1. numpy.random.Generator.shuffle